include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

custom_lint:
  rules:
    # Project uses [UncontrolledProviderScope] so we can disable this rule
    - missing_provider_scope: false
    # Disable this as we're still using old Provider for the GoRouter instance
    - avoid_manual_providers_as_generated_provider_dependency: false

linter:
  rules:
    - use_super_parameters
