name: ecommerce_app
description: FullStack Ecommerce App

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  equatable: 2.0.5
  flutter_staggered_grid_view: 0.7.0
  flutter_rating_bar: 4.0.1
  go_router: 14.6.0
  riverpod: 2.6.1
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  rxdart: 0.28.0
  sembast: 3.7.5+2
  sembast_web: 2.4.0+4
  path_provider: 2.1.5
  cached_network_image: 3.4.0
  firebase_core: 3.8.0
  firebase_auth: 5.3.3
  cloud_firestore: 5.5.0
  firebase_storage: 12.3.6
  flutter_stripe: 11.3.0
  flutter_stripe_web: 6.3.0
  pay: 2.0.0
  envied: 1.0.0
  algolia_helper_flutter: 1.1.0
  shimmer: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter    
  flutter_launcher_icons: 0.14.1
  build_runner: 2.4.13
  flutter_lints: 5.0.0
  custom_lint: 0.7.0
  riverpod_lint: 2.6.2
  mocktail: 1.0.4
  riverpod_generator: 2.6.2
  envied_generator: 1.0.0

# Workaround for this issue: https://github.com/algolia/algoliasearch-helper-flutter/issues/151
dependency_overrides:
  algolia_client_core: 1.27.1
  algolia_client_insights: 1.27.1
  algolia_client_search: 1.27.1
  algoliasearch: 1.27.1

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/app-icon.png"  
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    # Used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    # Add all product images
    - assets/products/

